### ISSUE TITLE
Support local server API

### ISSUE THREAD

**Issue by hsugene** [Smith8154/homebridge-airgradient#2]
**Is your feature request related to a problem? Please describe:**

No problems with the plugin at all, I’ve been using it for a bit and it’s been great. However, AirGradient had a server outage last night and I was thinking it would be cool if this plugin offered the option to use the local server API:

https://github.com/airgradienthq/arduino/blob/master/docs/local-server.md

**Describe the solution you'd like:**

Apart from the functionality that already exists, it might be cool to expose the LEDs and display as lights so that we could dim them with HomeKit scenes. 

**Describe alternatives you've considered:**

I have considered the more direct HomeKit integration described here: https://www.airgradient.com/integrations/airgradient-homekit/

But I would prefer to stick with the stock firmware. 

**Additional context:**

No additional context, except that I appreciate the effort you’ve put into building and sharing this!

**Comment by Smith8154** [comment]
I didn't even know this was possible! From the beginning I was hoping for local integration as I hate relying on cloud services for things in my home. I've been working on this and a few other things for a new release that should be ready shortly.

**Comment by hsugene** [comment]
That’s awesome, thanks for the update! Yeah, I think the local server functionality is relatively new. 

For a fully local setup, another alternative that I’ve tested is having the AirGradient report [via MQTT](https://www.airgradient.com/support/kb-mqtt-conf/) to [Mosquitto](https://mosquitto.org), and then have that connected to HomeBridge using the [MQTT-Thing plugin](https://github.com/arachnetech/homebridge-mqttthing#readme). 

It works ... but it’s a lot of extra installation/configuration if the AirGradient is the only MQTT device. And it still doesn’t let you set things like displayBrightness and ledBarBrightness, which (apparently) can be done with the local server API.

Anyway, looking forward to have you have in store! Thanks again.

**Comment by Smith8154** [comment]
This has been implemented in version 2.0.0. Waiting for NPM to finish their scheduled upgrade before I can push the package.

**Comment by Smith8154** [comment]
Pushed this to NPM last night.

**Comment by hsugene** [comment]
Wow, great! Is there a chance we could have the option to add the device by IP address or host name instead? 

I see that this works by connecting to airgradient_[serialno].local, which is supposed to work. Unfortunately for me, it’s not working. 

This is apparently an issue on Synology NAS devices, which is what I have Homebridge on. Something about the way that avahi is set up. I’ve been trying to figure out how to fix it, but no success so far. 

I figure if worked by hostname, then users could still enter airgradient_[serialno].local if desired, but they could also enter esp32c3-XXXXXX.localdomain or 192.168.20.79 if needed (which would both work on my setup). 

Either way, thanks for the update!
