### ISSUE TITLE
TVOC and NOx not showing up

### ISSUE THREAD

**Issue by Palandrel** [Smith8154/homebridge-airgradient#3]
**Describe The Bug:**

The TVOC(Ind40) and NOx values are not available in Controller or Eve apps. Temperature, humidity, CO2 and the different PMs are showing just fine.

**To Reproduce:**
Just install the plugin and make it available in HomeKit 

**Expected behavior:**

I am not expecting these values to be part of HomeKit air quality, nor I am expecting to see them in the Apple Home app. However, I would like to see them in Controller or Eve apps and be able to create automations with them.

**Logs:**

2024-08-25 09:18:54Airgradient BridgeLoaded plugin 'homebridge-airgradient'
2024-08-25 09:18:54Airgradient BridgeLoading 2 platforms...
2024-08-25 09:18:54Airgradient BridgeAirGradientPlatformDid finish launching
2024-08-25 09:18:55Airgradient BridgeBridge is running on port 51836.

**Plugin Config:**

{
  "platform": "ExampleHomebridgePlugin",
  "name": "Airgradient"
} 

**Screenshots:**

**Environment:**

* **Plugin Version**:1.0.4
* **Homebridge Version**: 4.3.1
* **Node.js Version**: 16.20.2
* **NPM Version**: 
* **Operating System**:  Hoobs box

**Comment by Smith8154** [comment]
Can you add a screenshot from the Eve app? I am able to see both TVOC and NOx values.

![image](https://github.com/user-attachments/assets/175ea4c2-1509-49e5-84bc-d043e41541d2)

**Comment by Palandrel** [comment]
Not sure what is going on. I checked my Airgradient devices in HomeKit and they were gone. In the Eve app, when I look at the Airgradient bridge, there is no device for that bridge. I have tried removing the bridge in both HomeKit and Hoobs then reinstall everything, still no device in HomeKit. It might be a server problem, I had issues this week. I had a plug-in that was spamming the log and fill up the storage faster than the system was purging it, so everything became sluggish. I manage to stop it and remove it. The system eventually partly recover and went from sluggish to slow. I am waiting on my Hoobs pro to rebuild the server. Until then, I am sorry but I won't be able to help.

You can close the bug report, I will retest it in a few months once I received the Hoobs pro.


Le 3 sept. 2024 à 10:08, Will Smith ***@***.***> a écrit :

﻿

Can you add a screenshot from the Eve app? I am able to see both TVOC and NOx values.

3C39D48A-01B1-490B-8F57-60FB517A2A54.png (view on web)<https://github.com/user-attachments/assets/175ea4c2-1509-49e5-84bc-d043e41541d2>

**Comment by Smith8154** [comment]
Closing per request.
